return {
    "stevearc/conform.nvim",
    opts = {
        formatters_by_ft = {
            php = { "pint" },
            javascript = { "prettier" },
            typescript = { "prettier" },
            typescriptreact = { "prettier" },
            css = { "prettier" },
            stylus = { "prettier" },
            scss = { "prettier" },
            sass = { "prettier" },
            html = { "prettier" },
            vue = { "prettier" },
            lua = { "stylua" },
        },
        format_on_save = false,
        formatters = {
            pint = {
                command = "pint.bat",
                args = { "$FILENAME" },
                stdin = false,
            },
            stylua = {
                args = {
                    "--column-width",
                    "80",
                    "--line-endings",
                    "Windows",
                    "--indent-type",
                    "Spaces",
                    "--indent-width",
                    "4",
                    "--quote-style",
                    "AutoPreferDouble",
                    "-",
                },
            },
            prettier = {
                prepend_args = {
                    "--tab-width",
                    "4",
                    "--print-width",
                    "80",
                    "--single-quote",
                    "true",
                    "--trailing-comma",
                    "es5",
                    "--html-whitespace-sensitivity",
                    "css",
                    "--prose-wrap",
                    "always",
                    "--jsx-single-quote",
                    "false",
                    "--bracket-same-line",
                    "false",
                    "--jsx-bracket-same-line",
                    "false",
                    "--single-attribute-per-line",
                    "true",
                },
                command = "prettier",
                args = {
                    "--stdin-filepath",
                    "$FILENAME",
                    "--config-precedence",
                    "prefer-file",
                },
            },
        },
    },
    keys = {
        {
            "<leader>f",
            function()
                require("conform").format({ async = true, lsp_fallback = true })
            end,
            mode = { "n", "v" },
            desc = "Format buffer or selection",
        },
    },
}
